### ISSUE TITLE
Rebuild with build plan metadata change errors

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/miniconda#98]
If I rebuild the [default app](https://github.com/paketo-community/miniconda/tree/v0.1.0/integration/testdata/default_app) by adding `build=true` metadata to `plan.toml`, the build fails.

### To reproduce

```
# checkout v0.1.0

./scripts/package.sh -v 8.8.8

cd integration/testdata/default_app

pack build minimage -b ../../../build/buildpackage.cnb -b gcr.io/paketo-community/build-plan
# Build succeeds

# now add build=true to plan.toml
cat plan.toml
[[requires]]
  name = "conda"

  [requires.metadata]
    launch = true
    build = true

pack build minimage -b ../../../build/buildpackage.cnb -b gcr.io/paketo-community/build-plan
===> DETECTING
[detector] paketo-community/miniconda  8.8.8
[detector] paketo-community/build-plan 0.0.11
===> ANALYZING
[analyzer] Restoring metadata for "paketo-community/miniconda:conda" from app image
===> RESTORING
===> BUILDING
[builder] Paketo Miniconda Buildpack 8.8.8
[builder]   Reusing cached layer /layers/paketo-community_miniconda/conda
[builder]
===> EXPORTING
[exporter] ERROR: failed to export: layer 'paketo-community/miniconda:conda' is cache=true but has no contents
```

### I expect

I expect that a new image is built where miniconda is available at build time for downstream buildpacks.
Right now it seems to fail with [this lifecycle error](https://github.com/buildpacks/lifecycle/blob/8d93e588101b22f1e8d3badb9274ebb4bf0894bc/exporter_test.go#L1333-L1349).

**Comment by ForestEckhardt** [comment]
I might push back on the idea that this scenario should work. I think that you may be a little deep in the guts of the machine for this to be a real world problem. I think that the extra overhead logic is not worth it in this case and instead we should maybe have a disclaimer that if you are manipulating the build plan between builds there may be caching issues that could be solved by clearing your build cache on a subsequent build.

**Comment by robdimsdale** [comment]
I'm inclined to agree with @ForestEckhardt - I don't think this is a problem that needs to be solved. I'm happy to be convinced otherwise, but I currently can't see a valid situation where a user interacts with the buildpack in this way.
